server:
  port: 9090
  server-header: Authorization
# Spring配置
spring:
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
    mapper:
      # 格式化JSON按照字典顺序排序
      sort-properties-alphabetically: true
  config:
    use-legacy-processing: true
  main:
    allow-circular-references: true
  profiles:
    active: dev
  data:
    elasticsearch:
      client:
        reactive:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

jwt:

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID




file:
  upload:
    path: D:\ProjectStoreg\

